services:
  - type: web
    name: virtualta-knowledge-base
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        value: 10000
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1 